name: Alexander Volkmann
markdown: kramdown
mathjax: true

redcarpet:
    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]


plugins:
  - jekyll-scholar
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata
  - jekyll-toc
  - jekyll-twitter-plugin
  - jekyll-relative-links
  - jekyll-seo-tag

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    line_numbers: table
    bold_every: 5
    

baseurl:  # must correspond to repository name for project sites
baseurlknitr: / # where servr::jekyll (i.e. knitr) looks for images
url: https://volkale.github.io/ # so links find their way back to homepage

google_analytics: UA-216099439-1
