name: Alexander Volkmann
markdown: kramdown
mathjax: true
plugins: ['jekyll/scholar']
redcarpet:
    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]


baseurl:  # must correspond to repository name for project sites
baseurlknitr: / # where servr::jekyll (i.e. knitr) looks for images
url: https://volkale.github.io/ # so links find their way back to homepage

giscus:
  repo:                "volkale.github.io"
  repo-id:             "127655812"
  category:            "Comments"
  mapping:             "pathname"
  label:               "comment"
  crossorigin:         "anonymous"
